### ISSUE TITLE
Failed to minify the code from this file:   ./node_modules/i18n-iso-countries/index.js:46

### ISSUE THREAD

**Issue by pontusvision** [michaelwittig/node-i18n-iso-countries#100]
version 3.7.0 seems to be missing ES5 libs, and is causing minify issues as described here:

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by michaelwittig** [comment]
is this related to #98 ?

**Comment by pontusvision** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Yes, I believe it is.                                                                                                                                                                          From: notifications@github.comSent: 27 June 2018 12:30 p.m.To: node-i18n-iso-countries@noreply.github.comReply to: reply@reply.github.comCc: lmartins@pontusnetworks.com; author@noreply.github.comSubject: Re: [michaelwittig/node-i18n-iso-countries] Failed to minify the code from this file: ./node_modules/i18n-iso-countries/index.js:46 (#100)  is this related to #98 ?

**Comment by michaelwittig** [comment]
duplicate
