### ISSUE TITLE
The English name of SZ is outdated

### ISSUE THREAD

**Issue by tjconcept** [michaelwittig/node-i18n-iso-countries#109]
As of the most recent ISO update, the name of SZ has changed.

**Comment by michaelwittig** [comment]
Hi @tjconcept Could you provide us with the new name?

**Comment by tjconcept** [comment]
It's in the ISO std.? https://www.iso.org/obp/ui/#iso:code:3166:SZ

**Comment by michaelwittig** [comment]
Great. Waiting until someone opens a PR.
