### ISSUE TITLE
de.json not correct sorted

### ISSUE THREAD

**Issue by sourcecode911** [michaelwittig/node-i18n-iso-countries#110]
Hey  :) 

First of all, thanks for this package :) 👍 
It would be nice, if kosovo is between "Kongo" and "Nordkorea" in de.json / en.json etc. for correct sort :)

**Comment by michaelwittig** [comment]
From the JSON spec:

> An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.

If you need them to be in order, sort them on your own. #84 might help
