### ISSUE TITLE
Missing countries data

### ISSUE THREAD

**Issue by iWooli** [michaelwittig/node-i18n-iso-countries#112]
Hi,
I can see that countries data are missing
- Martinique
- Netherlands Antilles
- South Korea
Best

**Comment by michaelwittig** [comment]
South Korea is available https://github.com/michaelwittig/node-i18n-iso-countries/blob/master/langs/en.json#L116
Martinique is available https://github.com/michaelwittig/node-i18n-iso-countries/blob/master/langs/en.json#L137

Netherlands Antilles (AN) is missing but under "Transitional reservations" https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Transitional_reservations

Feel free to open a PR for AN

**Comment by michaelwittig** [comment]
follow up issue #113
