### ISSUE TITLE
Language Codes

### ISSUE THREAD

**Issue by skipjack** [michaelwittig/node-i18n-iso-countries#122]
So I need something very similar to this library, but instead of ISO country codes to countries, I need to map ISO language codes to languages. I love the approach this library takes and I was wondering if...

a. You'd be open to a fork (renamed `node-i18n-iso-languages`).
b. Anyone would be interested in helping on the new package.

I'm happy to take the lead on it, but I figure there might be various native speakers who contributed here that could help me bootstrap the different `lang.json` files containing locale-specific language names.

I did find some similar projects for languages, but none as robust as this one...

- https://github.com/meikidd/iso-639-1
- https://github.com/shadiabuhilal/lang-list

Or, if someone does know of a robust alternative for languages instead of countries, please share.

**Comment by michaelwittig** [comment]
feel free to fork. I prefer small packages with a limited scope and not big ones. So a new package makes a lot of sense.
