### ISSUE TITLE
Incorrect statement about using it in nodejs, still require registerLocale

### ISSUE THREAD

**Issue by Bramzor** [michaelwittig/node-i18n-iso-countries#125]
Following statement seems invalid:

`If you use i18n-iso-countries with Node.js your are done. If you use the package in a browser environment you also have to register the languages you want to use to minimize file size.`

I'm using nodejs and it will show undefined for my queries until I add the countries.registerLocale specifically. I use it in angular like this: 
import * as countries from 'i18n-iso-countries';
Seems it was already mentioned here: #92

Any idea?

**Comment by michaelwittig** [comment]
You mention that you use Angular which implies that you are running in a browser environment, not Node.js?

**Comment by Bramzor** [comment]
You are absolutely right! Wow, I don't get how I made such an error. Thanks for pointing out my error 👍
