### ISSUE TITLE
Vietnam does not work?

### ISSUE THREAD

**Issue by matthiaslischka** [michaelwittig/node-i18n-iso-countries#162]
I know, it seems really strange. But `countries.getAlpha3Code('Vietnam', 'en')` returns `undefined`.

Any idea?
BR Matthias

**Comment by matthiaslischka** [comment]
Ok, seems your commit form 14.01. is not yet published to npm https://github.com/michaelwittig/node-i18n-iso-countries/commit/e5df6747eb36472f34be19b1dc8ccb08e5ad1b9b
"Vietnam" used to be "Viet Nam".

**Comment by michaelwittig** [comment]
version 5.0.0 is released now
