### ISSUE TITLE
Vietnamese translations invalid

### ISSUE THREAD

**Issue by lauzis** [michaelwittig/node-i18n-iso-countries#165]
Looks like Vietnamese translation is not valid, There is country names but looks like its English version not Vietnamese.
https://github.com/michaelwittig/node-i18n-iso-countries/blob/master/langs/vi.json

Incomperision this is what i got for translation from translator.

Albania | Albania
Andorra | Andorra
Australian Capital Territory (Australia) | Úc
Austria | Áo
Bahrain | Bahrain
Belarus | Bê-la-rút
Belgium | Bỉ
Bosnia and Herzegovina | Bosnia và Herzegovina
Brazil | Brazil
Bulgaria | Bulgaria
Canada | Canada
China | Trung Quốc
Croatia | Croatia
Cyprus | Cộng hòa Síp
Czech Republic | Cộng hòa Séc
Denmark | Đan mạch
Egypt | Ai Cập
Estonia | Estonia
Finland | Phần Lan
France | Pháp
Georgia | Georgia
Germany | Đức
Greece | Hy Lạp
Hungary | Hungary
Iceland | Ai-len
Indonesia | Indonesia
Ireland | Ai-len
Israel | Israel
Italy | Ý
Jordan | Jordan
Kazakhstan | Kazakhstan
Kuwait | Cô-oét
Latvia | Latvia
Lebanon | Lebanon
Liechtenstein | Liechtenstein
Lithuania | Litva
Luxembourg | Séc
Macedonia | Macedonia
Malta | Malta
Mexico | Mexico
Moldova | Moldova
Monaco | Monaco
Montenegro | Montenegro
Morocco | Ma-rốc
Netherlands | Hà Lan
New South Wales (Australia) | New South Wales (Úc)
New Zealand | New Zealand
Nigeria | Nigeria
Northern Territory (Australia) | Lãnh thổ phía Bắc (Úc)
Norway | Na Uy
Oman | Ô-man
Poland | Ba Lan
Portugal | Bồ Đào Nha
Qatar | Qatar
Queensland (Australia) | Queensland (Úc)
Romania | Rumani
Saudi Arabia | Ả Rập Saudi
Serbia | Serbia
Slovakia | Slovakia
Slovenia | Slovenia
South Africa | Nam Phi
South Australia (Australia) | Nam Úc (Úc)
Spain | Tây Ban Nha
Sweden | Thụy Điển
Switzerland | Thụy sĩ
Tasmania (Australia) | Tasmania (Úc)
Thailand | Thái Lan
Tunisia | Tunisia
Turkey | Turkey
Ukraine | Ukraine
United Arab Emirates | Các Tiểu Vương Quốc Ả Rập Thống Nhất
United Kingdom (UK) | Anh
United States of America | Mỹ
Victoria (Australia) | Victoria (Úc)
Vietnam | Việt Nam
Western Australia (Australia) | Tây Úc (Úc)
Yemen | Yemen

**Comment by ngdangtu-vn** [comment]
May I do this?
Also, should I use the transcript of just keep it as English one? Like Afghanistan -> Áp-ga-ni-xtan? The transcript isn't common so people may misunderstand.
