### ISSUE TITLE
Fix broken compatibility of getNames

### ISSUE THREAD

**Issue by danilofuchs** [michaelwittig/node-i18n-iso-countries#190]
This is an issue generated from this comment by @sebastien-prudhomme: https://github.com/michaelwittig/node-i18n-iso-countries/pull/175#issuecomment-638812851

Since https://github.com/michaelwittig/node-i18n-iso-countries/pull/175, `getNames` is not following the expected behaviour.
It may return either a name or a names array. This can break integrations and may require weird code to handle this inconsistency. Perhaps we should add an options parameter: `{ alternativeNames?: boolean }`.

By default, the library should return only the first name of the array (alternativeNames = false).

**Comment by ngdangtu-vn** [comment]
May I fix this issue? Today is late, so I will fix it and PR tomorrow.

**Comment by michaelwittig** [comment]
@ngdangtu-vn sounds good!
