### ISSUE TITLE
Great Britain vs United Kingdom

### ISSUE THREAD

**Issue by nitruxa** [michaelwittig/node-i18n-iso-countries#200]
Using this great project for sports app, and according to IOC (International Olympic Committee) `GBR` should stand for `Great Britain`, instead of `United Kingdom`. 👉  https://www.olympic.org/great-britain

Is this has to be fixed though, or added an IOC support? 🤔

**Comment by michaelwittig** [comment]
I suggest that you add it as an alternative name:

`"GB": ["United Kingdom", "UK"]` => `"GB": ["United Kingdom", "UK", "Great Britain"]`

**Comment by PPInfy** [comment]
Can I take this PR @michaelwittig ?

**Comment by michaelwittig** [comment]
sure, thanks @PPInfy

**Comment by nitruxa** [comment]
@michaelwittig I'll do Russian and Lithuanian languages PR later today 👍

**Comment by tibito** [comment]
Like @nitruxa said, this is a great project and I'm thinking using it for a sport's app as well, but I require IOC codes: https://simple.wikipedia.org/wiki/Comparison_of_IOC,_FIFA,_and_ISO_3166_country_codes.
Any plans to include them as a different code or, if I want to add them in my project, should they all be alternative names like @michaelwittig mentioned?

**Comment by michaelwittig** [comment]
@tibito I think you better write a tiny wrapper module that translates from IOC codes to ISO 3166 and vice versa before/after calling this module.
