### ISSUE TITLE
Incompatible with webpack

### ISSUE THREAD

**Issue by Oupsla** [michaelwittig/node-i18n-iso-countries#212]
Hello folks,

I'm using this project and I build it with webpack to send it in a lambda (aws).

Since this [PR](https://github.com/michaelwittig/node-i18n-iso-countries/pull/147) I unfortunately got a runtime error because this package tries to read the node_modules folder that doesn't exists (everything is wrapped into one file) and I get : `"ENOENT: no such file or directory, scandir 'node_modules/i18n-iso-countries/langs'"`

The require approach was better in my case cause webpack succeeded to wrap it, and now fails cause of the `fs.readdirSync(langDir);`

I can work on a PR to resolve this, what can be the solution to implement ?

I have at the moment rollback to version 5

**Comment by joakimsandstromfinnair** [comment]
We're facing the same issue with webpack packaged AWS Lambdas, so we also had to revert this package update. Would be nice to get a webpack compatible version. 

Or then some workaround how to get it functioning with webpack.

**Comment by michaelwittig** [comment]
I reverted #147 and released version 6.2.2
