### ISSUE TITLE
getAlpha3Code crash trying to call unexisting getAlpha2Code function on this

### ISSUE THREAD

**Issue by kristiannotari** [michaelwittig/node-i18n-iso-countries#214]
Environment: Node v14.15.0
package version: 6.2.2

My code:
```typescript
import { getAlpha3Code } from "i18n-iso-countries"

// ... stuff

export const myFunction = (value: string): string => {

   // ... stuff
    return getAlpha3Code(value, 'en')
}
```

Error:
```
{
    "errorMessage": "Cannot read property 'getAlpha2Code' of undefined",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError: Cannot read property 'getAlpha2Code' of undefined",
        "    at exports.getAlpha3Code (C:\\Users\\krist\\Documents\\Lavoro\\BePower\\beppe\\node_modules\\i18n-iso-countries\\index.js:328:21)",
        "    at parseAlpha3Code (webpack-internal:///./src/utils/parsers.ts:168:90)",
        "    at eval (webpack-internal:///./src/lambdas/input/projects/parser.ts:34:88)",
        "    at Array.map (<anonymous>)",
        "    at parseData (webpack-internal:///./src/lambdas/input/projects/parser.ts:31:21)",
        "    at eval (webpack-internal:///./src/lambdas/input/projects/lambda.ts:37:81)",
        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "    at eval (webpack-internal:///./src/utils/wrappers.ts:92:24)",
        "    at eval (webpack-internal:///./src/utils/wrappers.ts:68:16)",
        "    at eval (webpack-internal:///./src/utils/wrappers.ts:73:24)",
        "    at eval (webpack-internal:///./src/utils/wrappers.ts:50:24)",
        "    at eval (webpack-internal:///./src/utils/wrappers.ts:58:24)",
        "    at eval (webpack-internal:///./src/utils/wrappers.ts:34:24)"
    ]
}
```

Possible explanation:
I looked into the code within node_modules and it seems like you're trying to call `this.getAlpha2Code` from the `getAlpha3Code` function, resulting in the above error. It seems to me that `this` in that scope has not `getAlpha2Code` function declared, since it's just defined during `export.getAlpha2Code`.

Line: [328](https://github.com/michaelwittig/node-i18n-iso-countries/blob/183bcef494e74ce42f00554d4c518b0bdbd4844d/index.js#L328)

Forgive me if I am wrong here, just supposed after a brief look at your code.

**Comment by kristiannotari** [comment]
Small update

It used to work before I made some changes to the code. I changed the import of the lib from `import * as x from 'i18n-iso-countries'` to `import { getAlpha3Code } from 'i18n-iso-countries`.

Is it supposed to be a normal/correct behaviour?

**Comment by michaelwittig** [comment]
We should get rid of those this references and it should work "better". Feel free to open a PR
