### ISSUE TITLE
It is missing Netherlands Antilles "AN"

### ISSUE THREAD

**Issue by xavierlepretre** [michaelwittig/node-i18n-iso-countries#230]
As found here https://www.nationsonline.org/oneworld/netherlands_antilles.htm

**Comment by michaelwittig** [comment]
AN entry was deleted from ISO 3166-1 in 2016

see https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/iso_3166-1_newsletter_vi-8_split_of_the_dutch_antilles_final-en.pdf
