### ISSUE TITLE
Country names in Arabic [AR] start with a needless space

### ISSUE THREAD

**Issue by ZaidBarghouthi** [michaelwittig/node-i18n-iso-countries#233]
Hello,
![image](https://user-images.githubusercontent.com/26728749/108038970-25407380-7044-11eb-8b95-55d47e9c1012.png)

I have noticed that country names in Arabic have a space at the beginning (all except TT) and VA has 2 spaces at the begining!

**Comment by michaelwittig** [comment]
Thanks for the fix!
