### ISSUE TITLE
Dynamic require incompatible with bundler (browserify, webpack...)

### ISSUE THREAD

**Issue by Spy-Seth** [michaelwittig/node-i18n-iso-countries#24]
Recently change the way you load the lang file: https://github.com/michaelwittig/node-i18n-iso-countries/blob/7ede69e23f1af3771f7a49d63617b6141afae5df/index.js#L7-L10

Now you use a loop on all the defined code. Theses dynamics `require` call cannot be interpreted by code bundler (browserify or webpack). It's break the library: the `./langs/*.json` are not bundled with the application so loading of the lib fail.

Could you rollback to a more predictive loading ([like before](https://github.com/michaelwittig/node-i18n-iso-countries/commit/41ce5b464254d7a97e18aea115285174f84a5df1#diff-168726dbe96b3ce427e7fedce31bb0bcL13))? I know this make the maintenance harder for you but it's the only way to keep the compatibilities with these tools.

**Comment by michaelwittig** [comment]
released as i18n-iso-countries@1.2.1

**Comment by Spy-Seth** [comment]
Thanks for the fix.
