### ISSUE TITLE
TypeScript typings too optimistic

### ISSUE THREAD

**Issue by osdiab** [michaelwittig/node-i18n-iso-countries#258]
Some of the function types say that they'll return a string, but in fact often return `undefined`.

For example, if you use `getAlpha2Code("Laos", "en")`, then in fact you get `undefined`, not the stated `string` return type, because you were supposed to type `Lao People's Democratic Republic` (the fact that `Laos` doesn't match is a separate issue).

I'm willing to make a PR that makes these types more accurate to the true behavior of the library, but want to make sure that maintainers are OK with that change first.

**Comment by michaelwittig** [comment]
duplicate of #184 ?

**Comment by osdiab** [comment]
ah yeah duplicate - I'll push a pr to fix it! That one looks stale and I can do even better :)
