### ISSUE TITLE
Hong Kong and Taiwan issue

### ISSUE THREAD

**Issue by AlexanderSchoenfeld** [michaelwittig/node-i18n-iso-countries#266]
Hi! 

One of our customers came to us saying chinese customers are complaining about the country naming for `Hong Kong` and `Taiwan`.
Would it be possible to change these to `Hong Kong, China` and `Taiwan, China`?

We are currently getting all country names with `countries.getNames()`. 
If a general change is no good, how about adding an option like `{select: "china"}`?

I guess other users of this library also may have to change the naming.

**Comment by korbav** [comment]
Hi @AlexanderSchoenfeld,

Just to let you know, this request is not really a naive request from your customer and this request is correlated to one of the tensest geopolitical conflicts in the world.

My advice for you, if you agree to satisfy your customer's request, would be to manually remap the names. This is quite easy if you base to rely on the ISO codes, you can then name these countries whatever you wish.

My advice for the lib would be, of course, not to change a single letter and to stick to the most neutral position.

**Comment by AlexanderSchoenfeld** [comment]
Yeah, I know this is a geopolitical issue and I'm personally also not very happy about this change request.
Would it make sense to add these two as alias so the library could at least parse it?

**Comment by korbav** [comment]
> 
> 
> Yeah, I know this is a geopolitical issue and I'm personally also not very happy about this change request. Would it make sense to add these two as alias so the library could at least parse it?
> 
> Taiwan seems to have something like this in the english translation: `"TW": ["Taiwan, Province of China", "Taiwan"],`

That would be an option but would imply somehow to take a political stance, which doesn't sound quite legitimate with regards to the purpose of the library.

Could you rather use such a snippet ? 

```
const countries = require("i18n-iso-countries");

countries.registerLocale(require("i18n-iso-countries/langs/en.json"));

const replacements = {
  TW: "Taiwan replacement",
  HK: "HK replacement"
};
const countriesList = {
  ...countries.getNames("en", { select: "official" }),
  ...replacements
};
console.log(countriesList);

```

[https://codesandbox.io/s/damp-microservice-e42xc?file=/src/index.js:0-327](https://codesandbox.io/s/damp-microservice-e42xc?file=/src/index.js:0-327)

**Comment by michaelwittig** [comment]
See #255 #231 #16 ...

This lib uses the name as defined here https://www.iso.org/obp/ui/#iso:code:3166:TW

I'm well aware of the political issues behind this discussions but I'm not going to solve them in this lib. Anyone is free to create a fork with other names.
