### ISSUE TITLE
Uzbek cyrillic names

### ISSUE THREAD

**Issue by bahriddin** [michaelwittig/node-i18n-iso-countries#272]
Hi, 

thanks a lot for the project. I am thrilled to see Uzbek translation here but as you may know ([link to Wikipedia](https://en.wikipedia.org/wiki/Uzbek_alphabet) in case if you don't) we have 2 alphabets which we actively use: **latin** (which you already have) and **cyrillic**.
It would be great if there is a cyrillic version as well and I can create a PR. Only thing is I don't know how to add it.

Regards!

**Comment by michaelwittig** [comment]
Hi! There seems to b only one ISO 639-1 code for the language. We don't support languages outside of ISO 639-1 at the moment.

Adding a language is described here: https://github.com/michaelwittig/node-i18n-iso-countries#contribution

**Comment by bahriddin** [comment]
Yeah, that's why I was confused and created an issue.
Anyway, that's fine: I solved it for my case.

Thanks for the quick response.
