### ISSUE TITLE
Missing v7.4.0 tag

### ISSUE THREAD

**Issue by rokf** [michaelwittig/node-i18n-iso-countries#285]
Hi,

Could you please create and push a **v7.4.0** tag? The version [exists on NPM ](https://www.npmjs.com/package/i18n-iso-countries/v/7.4.0) but it's missing the tag on GitHub.

Thank you 😄

**Comment by michaelwittig** [comment]
Sorry. I forgot to push the tag... Thanks for reporting this @rokf
