### ISSUE TITLE
Sort countries by name

### ISSUE THREAD

**Issue by folivi** [michaelwittig/node-i18n-iso-countries#31]
Hi,
is there any easy way to sort the return of getNames by the value of the country name?

**Comment by thesbros** [comment]
They should already be sorted alphabetically. What are you looking to sort them by?

**Comment by folivi** [comment]
Unless I'm wrong I think countries are sorted by country code.
I had to this to get the list sorted by the country name for a given locale.

```
let avConuntryNames = Object.values(countries.getNames(locale)).sort();
 avConuntryNames.forEach(c => {
   availables[countries.getAlpha2Code(c, locale)] = c
})
```
