### ISSUE TITLE
Alias for South Korea

### ISSUE THREAD

**Issue by maxkre96** [michaelwittig/node-i18n-iso-countries#313]
Currently, in version 7.0 the  english name of south korea following ISO 3166/MA is not accepted by the package. 

Current Behavior:
i18nIsoCountries.getAlpha2Code("Korea, Republic of") -> undefined
i18nIsoCountries.getAlpha2Code("Republic of Korea") -> undefined
i18nIsoCountries.getAlpha2Code("South Korea") -> KR

Expected Behavior:
i18nIsoCountries.getAlpha2Code("Korea, Republic of") -> KR
i18nIsoCountries.getAlpha2Code("Republic of Korea") -> KR
i18nIsoCountries.getAlpha2Code("South Korea") -> KR

A Pull Request to add the alias has been proposed

**Comment by michaelwittig** [comment]
closed by #312
