### ISSUE TITLE
Missing countries Ascension Island and Tristan da Cunha

### ISSUE THREAD

**Issue by T-Lukashevich** [michaelwittig/node-i18n-iso-countries#318]
```
countries.getName('TA', 'en')  // undefined
countries.getName('AC', 'en') // undefined
countries.getName('US', 'en') // United States of America
```

Missing countries: 

- Ascension Island (+247 phone code, AC country code) 
- Tristan da Cunha (+290 phone code, TA country code)

**Comment by Seanathon** [comment]
Also missing the country, Kosovo (XK, XXK, 383)

**Comment by Seanathon** [comment]
Actually, just realized Kosovo is in there, but the code is incorrect.

**Comment by yukha-dw** [comment]
I believe they are part of Saint Helena, Ascension and Tristan da Cunha which is `SH`?

- SH: https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha
- SH-HL: https://en.wikipedia.org/wiki/Saint_Helena
- SH-AC: https://en.wikipedia.org/wiki/Ascension_Island
- SH-TA: https://en.wikipedia.org/wiki/Tristan_da_Cunha

**Comment by Callenowy** [comment]
@T-Lukashevich as @yukha-dw mentioned `Ascension Island` and `Tristan da Cunha` are part `Saint Helena, Ascension and Tristan da Cunha`: `SH`, `SHN`, `654`.

Reference:
https://www.iso.org/obp/ui/#iso:code:3166:SH

@Seanathon You are right. There is a wrong country code for Kosovo it should be `XKK` for `Alpha-3`.
But: 
> `XK` is a "user assigned" ISO 3166 code not designated by the standard, but used by the European Commission, Switzerland, the Deutsche Bundesbank, and other organizations. However, [ISO 3166-2:RS-KM](https://en.wikipedia.org/wiki/ISO_3166-2:RS) remains in use.

Reference: 
https://www.iso.org/obp/ui/#iso:code:3166:RS
https://en.wikipedia.org/wiki/Kosovo
