### ISSUE TITLE
Official name for Hong Kong - HK

### ISSUE THREAD

**Issue by koenig-dominik** [michaelwittig/node-i18n-iso-countries#327]
https://github.com/michaelwittig/node-i18n-iso-countries/blob/2a5a2a675e0550219d405ebe4a67361d85e936d5/langs/en.json#LL99C20-L99C20

The Official name for Hong Kong is probably "Hong Kong Special Administrative Region of the People's Republic of China" at least it says so on [wikipedia](https://en.wikipedia.org/wiki/Hong_Kong)

As the name is very long and confusing, you should probably not directly use the offical name. You already made an exception for [Korea](https://github.com/michaelwittig/node-i18n-iso-countries/blob/2a5a2a675e0550219d405ebe4a67361d85e936d5/langs/en.json#L116)
Wouldn't it be better to create another set of names instead of such exceptions?
I would propose
```js
console.log("HK (select: official) => " + countries.getName("GB", "en", {select: "official"})); // Hong Kong Special Administrative Region of the People's Republic of China
console.log("HK (select: alias) => " + countries.getName("GB", "en", {select: "alias"})); // Hong Kong SAR
console.log("HK (select: common) => " + countries.getName("GB", "en", {select: "common"})); // China Hong Kong
```

Our communications people from Shanghai proposed: `China Hong Kong` or `中国香港`

I have no clue about the translations.

**Comment by michaelwittig** [comment]
According to https://www.iso.org/obp/ui/#iso:code:3166:HK
the full name is: the Hong Kong Special Administrative Region of China
and the short name is: Hong Kong

So in the en.json file we could add:
```
"HK": ["the Hong Kong Special Administrative Region of China", "Hong Kong"],
```

To me, the official name seems to be quiet long as well. I personally never saw this name in use.

The name types are somewhat random. For me, official is what ISO says. Alias is what "western people" use.

I wonder if your issue is related to the fact that this lib is used by "non western" people as well and not everyone agrees on the same names for all countries. My idea (and it might not make sense in your case) is that we could add a new type to reflect the need for names used in China (and possible other areas in the future). My only concern here is that we quickly end up in a lot of discussions around country names.

**Comment by michaelwittig** [comment]
I see. We get this request often. So I guess we could also implement it here to solve the issue.
Would you be happy with a new types `china_official` and `china_alias` or something?
For countries where `china_official` is not defined, we fall back to `official`.
For countries where `china_alias` is not defined, we fallback to `alias`.

I can open a PR to implement this. I Also want to get rid of the array structure in the JSON files.
From:
```
"HK": ["the Hong Kong Special Administrative Region of China", "Hong Kong"],
```
to
```
"HK": [{
  "official": "the Hong Kong Special Administrative Region of China",
  "alias": "Hong Kong",
  "china_alias": "China Hong Kong"
}],
```

**Comment by koenig-dominik** [comment]
Somewhat off-topic:

Then what would you do for GB?
It has also 3 names defined but only 2 are actually "named"
"GB": ["United Kingdom", "UK", "Great Britain"],

For me this seems also a bit wrong as the official name for GB is "[the United Kingdom of Great Britain and Northern Ireland](https://www.iso.org/obp/ui/#iso:code:3166:GB)"

That's why i proposed a "common" country name by which a normal person would call it.

For the China problem: maybe add another field like "parentCountryCode": "ZH" like this you could implement a method to get the combined name of the parent and the normal name.
This would make it possible for anyone to choose whether they want to show the parent country or not.

Just a note to your plan to move away from arrays: this would probably bloat the bundle size for use in client side builds.
Maybe create a js file instead of json, this could theoretically be optimized by a bundler. (This would probably be a breaking change). There is a [json minimizer for webpack](https://webpack.js.org/plugins/json-minimizer-webpack-plugin/), but that is probably not included in 99% of projects.

**Comment by koenig-dominik** [comment]
Just another tought: The parent country stuff could actually also be handled in a different package as the data does not really have anything to do with the names itself.

**Comment by koenig-dominik** [comment]
We have fixed our particular issue by just replacing Hong Kong with China.

As it seems that the official names of most countries are not correct, it would probably be better to tackle that problem  in a  different issue.
