### ISSUE TITLE
USA should have 'of America' in its english name

### ISSUE THREAD

**Issue by vpithart** [michaelwittig/node-i18n-iso-countries#33]
I propose to set change english name from 
`"US": "United States"`
to
`"US": "United States of America"`

When using this library for search-as-you-type in 'select country' form input in english, entering `america` only shows `American Samoa` which looks weird.

I offer to create a branch and PR here if you permit me, or see attached diff.

[i18n-countries-USA-name-fix.diff.txt](https://github.com/michaelwittig/node-i18n-iso-countries/files/604977/i18n-countries-USA-name-fix.diff.txt)

**Comment by michaelwittig** [comment]
Hi @vpithart I released your change as i18n-iso-countries@1.7.1

**Comment by vpithart** [comment]
Thanks @michaelwittig for prompt reaction!
