### ISSUE TITLE
Possibility to load only specified languages?

### ISSUE THREAD

**Issue by qqilihq** [michaelwittig/node-i18n-iso-countries#36]
This module looks awesome and I would like to replace our self curated languages lists with it.

As I would like to use it in our web apps, my question: Is it possible to load only specified languages instead of the entire list? We would currently only require two languages and I would like to save transfer bandwidth.

**Comment by vpithart** [comment]
Yes, there is a way.

package.json
`"i18n-iso-countries": "^1.7.1"`

webpack.common.js. in module.exports:
```  
module: {
    exprContextCritical: false,
    rules: [
      {
        // Pack EN and FR only; don't load languages we don't need
        test: /node_modules\/i18n-iso-countries\/langs\/.*\.json$/,
        exclude: /langs\/(en|fr)\.json$/,
        loader: 'null-loader'
      },
      ... other rules
}
```

This way, only `en` and `fr` are webpacked. Footprint shrinks from 402 kB (all languages) to 118kB.

**Comment by qqilihq** [comment]
Thank you, vpithart! We're (still?!) using Browserify though, is there a similar mechanism?

**Comment by vpithart** [comment]
Don't know, sorry. Perhaps an impulse to switch to webpack?

**Comment by qqilihq** [comment]
Most definitely :)
