### ISSUE TITLE
Handle BCP47 Standard 

### ISSUE THREAD

**Issue by FKSI** [michaelwittig/node-i18n-iso-countries#47]
The [BCP47 Standard](https://msdn.microsoft.com/en-us/library/ms533052(v=vs.85).aspx) is the one where the locale is represented as follow:

`language`-`region`

For example: us-EN, us-UK

This great lib should handle that case. A simple `split('-')[0]` can do the trick

**Comment by michaelwittig** [comment]
To keep the scope limited, this library consumes `ISO 639-1`. If your format is different, you have somehow to convert it outside of the lib.
