### ISSUE TITLE
Handle withdrawn ISO-3166 codes

### ISSUE THREAD

**Issue by henhal** [michaelwittig/node-i18n-iso-countries#56]
On the referenced Wikipedia page there is a section with withdrawn codes: https://en.wikipedia.org/wiki/ISO_3166-1_numeric#Withdrawn_codes

I found myself getting data from a customer containing some of these withdrawn codes. 
Is there any reason not to include these as well? There should be no conflicts between current and withdrawn codes so I don't see any harm in returning data for a code that is officially no longer part of the standard but may still be in use?
Would you accept a PR adding these codes?

If needed, it could of course be made configurable, such as:

```
const countries = require('i18n-iso-countries')({includeWithdrawn: true});
const alpha2 = countries.numericToAlpha2('230');

```
or

```
const countries = require('i18n-iso-countries');
countries.configure({includeWithdrawn: true});
const alpha2 = countries.numericToAlpha2('230');

```

or, in each individual call:

```
const countries = require('i18n-iso-countries');
const alpha2 = countries.numericToAlpha2('230', {includeWithdrawn: true});

```

**Comment by michaelwittig** [comment]
Hi @henhal ,

I'm happy to accept your PR. I would prefer the first suggestion: config global and immutable:

```
const countries = require('i18n-iso-countries')({includeWithdrawn: true});
```

**Comment by henhal** [comment]
Hi @michaelwittig 

It turns out this was way more complex than anticipated. There are a number of withdrawn codes (https://en.wikipedia.org/wiki/ISO_3166-1_numeric#Withdrawn_codes), but the fate of these codes varies. While it would be possible to include mapping of these withdrawn codes to the country names at use at time of withdrawal, I fear this will make the data somewhat inconsistent.

The ISO standard has naturally been revised many times. Countries have been merged, split into several, changed names, changed only the alpha2 code etc etc. To keep track of this, a 4-letter code is being used in ISO3166-3. This page http://www.davros.org/misc/iso3166.html is quite old but gives a hint of the complexity.

For my particular application, the use case was banking, and in particular the fact that 280 is still used for Germany in banking applications (BIN/IIN etc), even though it actually represents West Germany which obviously is withdrawn since 1990. Apparently Germany has some kind of waiver for continued use of this withdrawn code in banking, supposedly for backwards compatibility reasons. 

Adding withdrawn entries could mess up things since there would no longer be a unique mapping from alpha2->numeric (e.g. both 276 and 280 would map to DE - so what should be returned when querying for DE?). 

For my particular use-case I will simply add logic to treat 280 as if it was 276. While I don't like hard-coded hacks, the fact that this is a well-known practice and afaik applies to just this one country makes it manageable.

**Comment by michaelwittig** [comment]
@henhal thanks for the detailed explanation! I agree with your conclusion.
