### ISSUE TITLE
Greek language code gr vs. el

### ISSUE THREAD

**Issue by pepe79** [michaelwittig/node-i18n-iso-countries#57]
Hello,

since a few days greek is supported as language, using the getName(country, language) function. But I wonder why the language code was renamed from el to gr in this commit:

https://github.com/michaelwittig/node-i18n-iso-countries/pull/51/commits/a33123162d6287ec1451bd85cd6c75c7f6d6998d

I thought that ISO_3166-1 define countries and e.g. iso 639 define language codes? Since you can also pass "ar" as language, which in this context is the language code from "arabic" and not the country "argentina". So it is only consequent to use "el" instead of "gr" as language code, when you mean greek (the language). 

I think I am also confused, because the documentation of the getName function does not clearly state, what iso-definition the language-parameter should conform to.

**Comment by michaelwittig** [comment]
the language should follow https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

as you said: `el`  is correct, not `gr`

**Comment by michaelwittig** [comment]
released as `i18n-iso-countries@2.0.0`

since this is a breaking change we are now on version 2 :)

**Comment by pepe79** [comment]
sorry about that :)
