### ISSUE TITLE
Uses includes for Angular 2/4?

### ISSUE THREAD

**Issue by sinzen** [michaelwittig/node-i18n-iso-countries#60]
Hi,

My question is can I use this library on angular project?

I have this error on compilation: 
`You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:6)` on `i18n-iso-countries/langs/ar.json Unexpected token (2:6)
`

Thanks

**Comment by michaelwittig** [comment]
Actually, I have no idea :) I'm not an user of Angular 2 or 4. If anyone else has any idea what is needed, please let us know.

**Comment by Ephys** [comment]
@sinzen That sounds like a webpack configuration error. If you're using webpack 1 you need to add [`json-loader`](https://github.com/webpack-contrib/json-loader), in webpack 2 it is loaded by default.

Also make sure the file isn't excluded from being processed by webpack in your configuration.

**Comment by michaelwittig** [comment]
could you try the new 3.x release that includes #64

**Comment by swftvsn** [comment]
Yes you can.

I think we should work out nicer way to include select language files to Angular apps, but for now one can use this:

First, declare System and import i18n-iso-countries:
