### ISSUE TITLE
Missing country code 'IC'

### ISSUE THREAD

**Issue by timbertus** [michaelwittig/node-i18n-iso-countries#62]
The country code for the Canary Islands is currently not supported by the library.

**Comment by michaelwittig** [comment]
can you provide a source which mentions that IC is a ISO 3166 country code? I can't find it.

**Comment by timbertus** [comment]
I only found a german source on Wikipedia: https://de.wikipedia.org/wiki/ISO-3166-1-Kodierliste

**Comment by michaelwittig** [comment]
It says: "Exceptionally reserved code in ISO 3166-1. This code exists only for use in other standards (for example SWIFT code) and **should not be used for coding according to ISO 3166-1**."

**Comment by michaelwittig** [comment]
this is related to #50
