### ISSUE TITLE
Optimizing for browsers

### ISSUE THREAD

**Issue by Ephys** [michaelwittig/node-i18n-iso-countries#63]
This is a really cool library but bundling it for usage in a browser results in a massive bundle (146KB for a bundle containing only this library, post-minification, pre-gzip).

Optimizing it wouldn't be too hard and, even while it would require a tiny bit more work on the developers that use this library I believe it would be definitely worth it.

---

First optimization that can be done is not loading all locales at once but only those needed by the app. There are a couple ways you can do this:

1. By first registering the locale the app needs:

```javascript
const countries = require('i18n-iso-countries');

countries.registerLocale(require('i18n-iso-countries/locales/en.json'));
countries.getNames('en'); // returns the list of names in english

countries.getNames('fr'); // throws "unknown locale, please register it first"
```

2. Or the date-fns way, where the locale object is used directly:

```javascript
const countries = require('i18n-iso-countries');
const en = require('i18n-iso-countries/locales/en.json');

countries.getNames(en); // returns the list of names in english
```

If you wish to keep the "all locales are pre-loaded" behavior on node, you can specify a different entrypoint for browsers than for node in `package.json` and have the node entrypoint register all locales then call the browser entrypoint.

---

Second optimization is getting rid of the [`pad`](https://www.npmjs.com/package/pad) dependency. The reason behind it is that this library is itself dependant on [`wcwidth`](https://www.npmjs.com/package/wcwidth), which itself is dependant on [`defaults`](https://www.npmjs.com/package/defaults), which itself uses [`clone`](https://www.npmjs.com/package/clone).

That's a massive amount of code for something like `pad`, even more now that `String.prototype.pad{Start|End}` is standard and really easy to polyfill.

The best way to optimize this would be to simply use `String.prototype.pad{Start|End}` instead of `pad`, and add a note in the documentation stating that the environment needs to provide a polyfill for that function if it is not natively available. ([`core-js`](https://github.com/zloirock/core-js) can provide these polyfills)

---

I can submit a PR with all this if you are interested.

Thank you :)

**Comment by michaelwittig** [comment]
PR is very welcomed. Your knowledge is way higher than mine on that topic

**Comment by Ephys** [comment]
Perfect, I'll do it as soon as possible!

**Comment by Ephys** [comment]
Merged :)
