### ISSUE TITLE
Add alternate / shorter names?

### ISSUE THREAD

**Issue by exogen** [michaelwittig/node-i18n-iso-countries#70]
Hi @michaelwittig!

I was using this library and figured I'd let you know why I had to switch to another library for ISO 3166 lookup, in case there is an opportunity for improvement.

So far as I can tell, the actual ISO specification does indeed list the name for the US as "United States of America", and I see the issue #33 where this was changed. The problem is that every other ISO 3166 library I've used (and I've tried a bunch) all return "United States".

This is affecting interoperability for me: for example, when I query the [Last.fm geo API](https://www.last.fm/api/show/geo.getTopTracks), the `country` parameter expects a country *name*, not a *code* (extremely weird decision on their part, I know). But now I can't use this library to do the conversion, because the API expects "United States" and fails for "United States of America".

Are all the other libraries and Last.fm are just using outdated ISO 3166 databases? Or is there a short & long name and each library is only exposing one or the other? If this library's purpose is for printing nice i18n strings that's fine, I just figured I'd let you know about this use case in case you want more ISO 3166 interoperability.

**Comment by CarloPalinckx** [comment]
Same goes for the translation of Luxembourg in `nl_NL`. It is printed as `Luxemburg, Groot-Hertogdom` instead of just `Luxemburg`. @exogen which library did you switch to if I may ask?

**Comment by exogen** [comment]
@CarloPalinckx Sure, I ended up going with [country-list](https://www.npmjs.com/package/country-list) for my use case

**Comment by StephanGeorg** [comment]
Hi @exogen @CarloPalinckx and @michaelwittig 

I had exactly the same problem that's why I wrote [iso-countries-lookup](https://github.com/StephanGeorg/iso-countries-lookup). It's based on node-i18n-iso-countries and [countries](https://github.com/mledoze/countries) and has some basic fault tolerance for inputs.
