### ISSUE TITLE
I see weird characters in countries name in German language

### ISSUE THREAD

**Issue by forethoughtde** [michaelwittig/node-i18n-iso-countries#72]
Can I know why do I receive weird characters in countries name in German language?

SÃ¼dafrika
SÃ£o TomÃ© und PrÃ­ncipe
SÃ¼dsudan
Russische FÃ¶deration
SÃ¼dkorea
FranzÃ¶sisch-Guayana
Vereinigtes KÃ¶nigreich GroÃbritannien und Nordirland

Have anyone experienced this problem?

**Comment by michaelwittig** [comment]
where do yo use this characters? in your app, editor, ...

**Comment by forethoughtde** [comment]
In my website. It was because I did not use the meta for charset. 

`html
    <META HTTP-EQUIV="content-type" CONTENT="text/html; charset=utf-8">
`
