### ISSUE TITLE
"Libya" has become "State of Libya"

### ISSUE THREAD

**Issue by minotogna** [michaelwittig/node-i18n-iso-countries#73]
Hello Michael,

Please, take note that "Libya" has become "State of Libya".
Would it be possible to update it?

Thank you,
Mino

**Comment by michaelwittig** [comment]
The countries names are not the official names, but the names that are usually used.

E.g. I live in Germany which officially is called Federal Republic of Germany, but no one uses the long name.

If I understand correctly, the same is true with Libya?

**Comment by minotogna** [comment]
Yes, you are right.

I got confused for a moment; let me explain you why.

Since i work for an intergovernmental organization, we received a communication from their government to use the official name everywhere they are mentioned, including software.

At the same time, we have also received instructions from our communication department we must use the official names that they (the comm. dep.) publish.
For this reason i cannot use anymore this library... it was making my life easier, but i'm sorry i cannot use it for this specific software now..

But please, keep it up to date, as i think it's great and beneficial for many!

Thank you again!
Mino
