### ISSUE TITLE
List of country codes

### ISSUE THREAD

**Issue by piranna** [michaelwittig/node-i18n-iso-countries#74]
Add function to fetch list of country codes, something similar to

```js
const countryCodes = require('i18n-iso-countries/codes.json').map(info => info[0])
```

**Comment by michaelwittig** [comment]
Something like this?

```
Object.keys(countries.getAlpha2Codes());
Object.keys(countries.getAlpha3Codes());
Objct.keys(countries.getNumericCodes());
```

**Comment by piranna** [comment]
Yeah, `Object.keys()` is a solution, but since data is already being processed from the JSON, I find it would be good to also offer natively the list of country codes :-)
