### ISSUE TITLE
Add method `isValid`

### ISSUE THREAD

**Issue by abelosorio** [michaelwittig/node-i18n-iso-countries#77]
I need a method to validate a country code. Currently I'm doing `toAlpha3(code) !== undefined`. But I'd prefer that logic to be encapsulated into the `node-i18n-iso-countries` package and to call a simple `isValid` method.

**Comment by abelosorio** [comment]
I wrote the method, including tests and changes on README but I don't have any permissions to create the PR. Is there any way to submit it?

Thanks

@michaelwittig

**Comment by michaelwittig** [comment]
Hi @abelosorio why don't you have permissions to open a PR? You fork this repo and and push your changes usually in a branch != master and then you can open a PR?

If this doesn't work, feel free to send me the patch to post@michaelwittig.info

**Comment by abelosorio** [comment]
Oh OK thanks @michaelwittig. I haven't done this before.

Thanks.

**Comment by abelosorio** [comment]
Done @michaelwittig :point_up: 

Let me know if it needs any change.

Cheers.

**Comment by michaelwittig** [comment]
Great. I added a small comment to your pull request.
