### ISSUE TITLE
Feature request: add language names

### ISSUE THREAD

**Issue by serhiipalash** [michaelwittig/node-i18n-iso-countries#79]
Hi! You have a great library!

Is it possible to add language names translations to your library or you only work  with country names?

It would be great to add this data with similar api https://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by michaelwittig** [comment]
Hi @serhiipalash I believe that's out of scope for the project.

We focus on returning a country name (using ISO 3166-1 country codes to identify the country) for a language (using ISO 639-1 codes to identify the language).

**Comment by serhiipalash** [comment]
Ok thanks.

**Comment by e110c0** [comment]
@michaelwittig would you mind a fork of i18n-iso-countries for exactly that purpose? (so i18n-iso-languages)

I like the interface and the 639 packages available are all focussed on language names in English and in "native", which does not always is enough
