### ISSUE TITLE
ISO 3166-2 subdivision codes

### ISSUE THREAD

**Issue by WaSa42** [michaelwittig/node-i18n-iso-countries#80]
Is it possible to complete the list with some essential ISO 3166-2 subdivision codes like https://en.wikipedia.org/wiki/ISO_3166-2:GB
* GB-ENG - England
* GB-NIR - Northern Ireland
* GB-SCT - Scotland
* GB-WLS - Wales

I can make a PR if this is something you want to add.

**Comment by michaelwittig** [comment]
HI @WaSa42 I believe that's out of scope for the project. 

We focus on returning a country name (using ISO 3166-1 country codes to identify the country) for a language (using ISO 639-1 codes to identify the language).

But I believe that this would be a good idea for a new npm package!
