### ISSUE TITLE
Alphabetical country list

### ISSUE THREAD

**Issue by timothyarmes** [michaelwittig/node-i18n-iso-countries#84]
Hi,

It would be nice to have a function to return an array of country names, with their codes, sorted alphabetically by the locale. Useful for drop down lists.

**Comment by timothyarmes** [comment]
Actually I think that this is so simple for us to do that it makes no sense to have it in the library. ..

```
  const countryOptions = Object.keys(countryNames)
      .map(key => ({ value: key, label: countryNames[key] }))
      .sort((a, b) => a.label.localeCompare(b.label));
```

**Comment by mrleblanc101** [comment]
I suggest only doing a localCompare on the first letter if you want country with accented character in their name to be grouped togerther.

Without `chartAt(0)`:
<img width="414" alt="Capture d’écran, le 2021-08-02 à 11 36 21" src="https://user-images.githubusercontent.com/17392251/127887192-23cc6b03-c208-4d43-86c5-35cffe0cd9a2.png">

With `charAt(0)`:
<img width="412" alt="Capture d’écran, le 2021-08-02 à 11 35 55" src="https://user-images.githubusercontent.com/17392251/127887195-5ed477f3-d1dc-4663-9290-b5b0b1ad2eb4.png">

```
            const countryNames = countries.getNames(this.$i18n.locale, { select: 'official' });
            return Object.keys(countryNames)
                .map((key) => ({ value: key, label: countryNames[key] }))
                .sort((a, b) => a.label.charAt(0).localeCompare(b.label.charAt(0)));
```

**Comment by mrleblanc101** [comment]
Nvm this actually create more problem as the now the second letter is not taken into account for country that start with the same letter. I'm looking to sort alphabetically but accented country should have their own grouping.
