### ISSUE TITLE
[PULL] Add a better way to register locales

### ISSUE THREAD

**Issue by ExNG** [michaelwittig/node-i18n-iso-countries#95]
Hello,

i noticed that my code using your package was returning an empty Dict:
```javascript
require('i18n-iso-countries').getNames('de') // {}
```

And so i was wondering what changed, it may be that i updated your package and something broke,
so looked into your code and saw that `registeredLocales` is by default empty and you have to "import" languages by require.
Would you be interested for me to create a pull request which adds a method like following:
```javascript
const c = require('i18n-iso-countries').import('de') // or 'en ' or 'fr'
// instead of
const c = require('i18n-iso-countries')
c.registerLocale(require('i18n-iso-countries/langs/de.json'))
```
... that would be much better to use than having to require a json by path.

Otherwise i really appreciate your work here :+1:

**Comment by michaelwittig** [comment]
I like the `import` idea and I'm happy to merge this change
