### ISSUE TITLE
Angular 6 need to register locale to make it works

### ISSUE THREAD

**Issue by lippomano** [michaelwittig/node-i18n-iso-countries#97]
I am using node.js (Angular 6) but I need to register the locale data if I want to use it.
Is it correct?

I need to translate it into multiple languages, I can't register only 2 languages.

**Comment by michaelwittig** [comment]
You can call the `registerLocale` function as often as you like with one of the values from this list: https://github.com/michaelwittig/node-i18n-iso-countries#supported-languages-iso-639-1
